POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vaSIsImlkIjoiNjE1ODdmOGEwNDEyZjkxZjNjZjk0MGQ2IiwiaWF0IjoxNjMzMTkwOTU2fQ.n9GWLthzyw3un4RxvW2JL3AqwsJOdfco4XiNEdSTZ4E

{
    "title": "Title",
    "author": "author",
    "url": "url",
    "likes": 102
}